---
abstract: 'An OO interface to the Digital Ocean API.'
author:
  - 'Adam Hopkins <srchulo@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DigitalOcean
no_index:
  directory:
    - t
    - inc
requires:
  JSON::XS: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Method::Signatures::Simple: 0
  Mouse: 0
  MouseX::Types: 0
  Object::Tiny::RW::XS: 0
  Object::Tiny::XS: 0
  perl: 5.006
version: 0.08
